config/routes.rb
Rails.application.routes.draw do
  root 'questions#index'

  resources :questions do
    post '/vote' => 'votes#vote_handler'
    resources :responses
    resources :answers do
      resources :responses
    end
  end

  resources :users, only: [:index, :show, :new, :create]

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  namespace :admin do
    root "users#index"
    resources :users, except: [:new]
    resources :answers
    resources :responses
    resources :questions
  end

end

app/models/question.rb
class Question < ActiveRecord::Base
  include PostedAt

  belongs_to :user
  has_many :answers
  has_many :question_tags
  has_many :tags, through: :question_tags
  has_many :votes, as: :votable
  has_many :responses, as: :respondable

  validates :title, :content, :user_id, presence: true
  validates :title, uniqueness: true
  validates :title, length: { maximum: 90 }
  validates :content, length: { maximum: 10000 }
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < ApplicationController
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :update, :destroy, :edit]
  before_action :authenticate_user, only: [:create, :new]
  def index
    @questions = Question.order(:posted_at).limit(25) # Come back and implement pagination?
  end

  def show
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    @question.user_id = session[:user_id]
    if @question.save
      redirect_to @question
    else
      render 'new' # Need to flash errors here
    end
  end

  def update
    if @question.update(question_params)
      redirect_to @question, notice: 'Question was updated successfully."'
    else
      render :edit
    end
  end

  def destroy
    @question.destroy
    redirect_to root_path
  end

  private

  def set_question
    @question = Question.find(params[:id])
  end

  def question_params # Gonna have to add more stuff here
    # Have to add current_user.id
    params.require(:question).permit(:title, :content)
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def truncate_content(question, number)
    if question.content.length > number
      (question.content[0..number] + " " + link_to("... continue reading", question)).html_safe
    else
      question.content.html_safe
    end
  end
end

app/views/questions/_form.html.erb
<section class='generic-form'>
  <h2><%= yield(:title) %></h2>
  <%= form_for(@question) do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title, placeholder: "Question Title" %>
    <%= f.label :content %>
    <%= f.text_area :content, placeholder: "Your Question" %>
    <%= f.submit "Ask" %>
  <% end %>
</section>

app/views/questions/_question_display.html.erb
<h2>
  <%= @question.title + "?" %>
</h2>
Tagged: <% @question.tags.each do |tag| %>
  <%= tag.word %>
<% end %>
<h4>
  Asked by <%= link_to @question.user.username, @question.user %>, <%= format_date(@question.posted_at) %>
</h4>
<div>
  <p class='question-content'><%= @question.content %></p>
</div>

app/views/questions/edit.html.erb
<%= content_for :title, "Edit Question" %>

<%= render 'form' %>

app/views/questions/index.html.erb
<% content_for :title, "Questions Index" %>
<section id='show-questions-index'>
  <h2>RECENT QUESTIONS </h2>
  <% @questions.each do |question| %>
    <section class='question'>
        <h3><%= link_to question.title, question %></h3>
      <span><%= truncate_content(question, 200) %></span>
      <h5>
        Asked by <%= link_to question.user.username, question.user %> <%= format_date(question.posted_at) %>
      </h5>
      <a id='<%= question.id %>' class='vote-arrow  <%= current_user_upvoted(question) if logged_in? %>' href='#'>&#9650</a>Upvotes: <span id='<%= question.id %>-vote-count'><%= question.votes.count %></span> |
      Answers: <%= question.answers.count %> |
      Responses: <%= question.responses.count %> |
      Tags: <% question.tags.each do |tag| %>
        <%= tag.word %>
      <% end %>
    </section>
  <% end %>
</section>

app/views/questions/new.html.erb
<%= content_for :title, "New Question" %>

<%= render 'form' %>

app/views/questions/show.html.erb
<% content_for :title, @question.title %>
<a id='<%= @question.id %>' class='vote-arrow <%= current_user_upvoted(@question) if logged_in? %>' href='#'>&#9650</a>Upvotes: <span id='<%= @question.id %>-vote-count'><%= @question.votes.count %></span>
<nav>
  <%= link_to 'Give Answer', new_question_answer_path(@question.id), id: 'but' %>
</nav>
<section id='show-question' class='question'>
  <%= render 'question_display' %>
  <div class='option-links'>
    <% if current_user %>
      <% if current_user.id =! @question.user.id %>
        <%= link_to "Edit", edit_question_path %> <%= link_to "Delete", question_path(@question), method: :delete, data: { confirm: 'Are you certain you want to delete this?' } %>
      <% end %>
      <%= link_to 'Add Comment', new_question_response_path(@question.id), id: "response-link" %>
    <% end %>
  </div>
  <%= @responses %>
  <ul>
    <% @question.responses.each do |response| %>
      <li class='response'>
        <p>
          <%= response.content %>
        </p>
        <h5>Response by <%= response.user.username %>, <%= format_date(response.posted_at) %></h5>
      </li>
    <%end%>
  </ul>
</section>
<section id='show-answers' class='answers'>
  <% @question.answers.each do |answer|  %>
    <% @answer = answer %>
    <%= answer.content %>
    <h5> Answer by <%= answer.user.username %>, <%= format_date(answer.posted_at)%></h5>
    <%= link_to 'Add Comment', new_question_answer_response_path(@question.id, @answer.id), id: "response-link" %>
    <ul>
      <% answer.responses.each do |response| %>
      <li class='response'>
        <p>
          <%= response.content%>
          Response by <%= response.user.username %>, <%= format_date(response.posted_at) %>
        </p>
      </li>
      <%end%>
    </ul>
  <%end%>

</section>