config/routes.rb
Rails.application.routes.draw do
  root 'questions#index'

  resources :questions do
    post '/vote' => 'votes#vote_handler'
    resources :responses
    resources :answers do
      resources :responses
    end
  end

  resources :users, only: [:index, :show, :new, :create]

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  namespace :admin do
    root "users#index"
    resources :users, except: [:new]
    resources :answers
    resources :responses
    resources :questions
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id='site-wrapper'>
    <header>
      <%= link_to "Meta<br>over<br>flow".html_safe, root_path, class: 'site-title' %>
    </header>
    <nav>
        <%= link_to 'Questions', questions_path %>
        <%= link_to 'Users', users_path  %>
        <% if current_user %>
          <%= link_to('Logout', logout_path)%>
        <% else %>
          <%= link_to_if(current_user.nil?, 'Login', '/login') %>
          <%= link_to_if current_user.nil?, 'Register', new_user_path %>
        <% end %>
        <hr>
        <%= link_to "Ask a<br> question".html_safe, new_question_path %>
      </nav>
    <div id="container">
      <% flash.each do |key, value| %>
        <div class="alert-alert" <%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
    </div>
  </div>
  </body>
</html>